### ISSUE TITLE
UTF-8 encoding/decoding bug (German Umlauts)

### ISSUE THREAD

**Issue by necrevistonnezr** [WangQiru/mercury_fulltext#2]
Thank your for this plugin. Works great with english feeds.

However, special characters like German Umlauts don't seem to be supported, resulting in garbled text (see screenshot attached). I don't have similar problems when e.g. using Mercury in the iOS Reeder App.
![rss missmuti de_ f 153 c 0_-_2017-06-08_13 16 17](https://user-images.githubusercontent.com/8191935/26926140-ad67ca6c-4c4c-11e7-82ab-ff8402fe9cc0.png)

**Comment by HenryQW** [comment]
Adding encoding in post requests should resolve it. What’s the encoding for Umlauts? UTF-8?

**Comment by necrevistonnezr** [comment]
Yes, seems so: http://www.periodni.com/unicode_utf-8_encoding.html#german_special_characters

**Comment by HenryQW** [comment]
@necrevistonnezr  can you try this branch? [UTF-8 encoding](/WangQiru/mercury_fulltext/tree/encoding)

**Comment by necrevistonnezr** [comment]
Installed the other branch. Still the same, unfortunately....
Feed address is http://www.mediabiz.de/rss/news
![2445 _tiny_tiny_rss_-_2017-06-09_10 48 31](https://user-images.githubusercontent.com/8191935/26968155-41dcf3f2-4d01-11e7-9e4d-0e33be5ba1e5.png)

**Comment by HenryQW** [comment]
Try again, should be fine now? @necrevistonnezr 
<img width="768" alt="screen shot 2017-06-09 at 18 32 50" src="https://user-images.githubusercontent.com/5896343/26987160-5d4053e6-4d42-11e7-986e-b0d2d03ddf46.png">
